export type StaticAdvocate = {
  name: string;
  city: string;
  barId?: string;
  court?: string;
  verified?: boolean;
};

// ── VERIFIED ADVOCATES (with Bar Council ID & Court) ── ON TOP ──
export const verifiedAdvocates: StaticAdvocate[] = [
  { name: "Gudooru Sai Kumar Netha", city: "Hyderabad", barId: "TS/3268/2021", court: "High Court", verified: true },
  { name: "Dharma Rajinikar Reddy", city: "Hyderabad", barId: "TS/3268/2021", court: "High Court", verified: true },
  { name: "M. Gopal Rao", city: "Hyderabad", barId: "TS/2002/2013", court: "High Court", verified: true },
  { name: "Raghavendra Reddy K", city: "Hyderabad", barId: "TS/2187/2016", court: "High Court", verified: true },
  { name: "Kandukuri Narasimha Chary", city: "Hyderabad", barId: "TS/2234/2008", court: "High Court", verified: true },
  { name: "Gottipamula Sharanya", city: "Bhongir", barId: "TS/1548/2024", court: "District Court Bhongir", verified: true },
  { name: "Suresh Kumar K", city: "Hyderabad", barId: "TS/2646/2015", court: "High Court", verified: true },
  { name: "Soumya Sree", city: "Ramagundam", barId: "TS/1678/2024", court: "High Court of Telangana", verified: true },
  { name: "Ankani Abhishek", city: "Sircilla", barId: "3155/23", court: "Rajanna Sircilla", verified: true },
  { name: "Baddam Sharannteja Goud", city: "Hyderabad", barId: "2295/2023", court: "High Court, RR Dist Court", verified: true },
  { name: "Anil Babu Gajja", city: "Podili", barId: "AP/2090/2021", court: "Podili, Darsi, Kanigiri, Markapur", verified: true },
  { name: "Sneha Gudikadi", city: "Hyderabad", barId: "2365/2023", court: "Ranga Reddy District Court & High Court", verified: true },
  { name: "Yangala Mounika", city: "Ongole", barId: "AP/167/2021", court: "District Court, Prakasam", verified: true },
  { name: "Sandadi Venkateswarlu", city: "Ongole", barId: "AP/2206/2018", court: "District Court Ongole", verified: true },
  { name: "Ramyagopika", city: "Vijayawada", barId: "AP/2974/2023", court: "Vijayawada", verified: true },
  { name: "Ananda Kumar Vejandla", city: "Vijayawada", barId: "AP/681/2022", court: "High Court of Andhra Pradesh", verified: true },
  { name: "Vidyasagar Chettaboiena", city: "Hanmakonda", barId: "3695", court: "Warangal", verified: true },
  { name: "Srinivas Nuthalapati", city: "Tenali", barId: "AP460/2023", court: "High Court", verified: true },
  { name: "Sudhakar Pedda Yammanuru", city: "Guntakal", barId: "AP/161/2024", court: "Guntakal", verified: true },
  { name: "Shanthi Hari", city: "Hyderabad", barId: "18109", court: "High Court", verified: true },
  { name: "Talari Rajeswari", city: "Vijayawada", barId: "AP676/2022", court: "AP High Court", verified: true },
  { name: "Sandeep Pamarati", city: "Mangalagiri", barId: "AP/646/2022", court: "AP High Court", verified: true },
  { name: "Sonti Gopikrishna", city: "Mangalagiri", barId: "AP/1479", court: "High Court of Andhra Pradesh", verified: true },
  { name: "Kandula Rajyalaxmi", city: "Hayatnagar", barId: "TS/3216/2017", court: "Rangareddy", verified: true },
  { name: "Kommu Ramachandrudu", city: "Dhone", barId: "AP/1075/2025", court: "Prl JCJ Court, Dhone, Nandyal", verified: true },
  { name: "Borampeta Sureshkumar", city: "Hyderabad", barId: "TS/152/2021", court: "All Courts", verified: true },
  { name: "Moiz Attari", city: "Hyderabad", barId: "23666", court: "City Civil Court", verified: true },
  { name: "Satyanarayana Bodla", city: "Karimnagar", barId: "TS/2446/2024", court: "Karimnagar Court", verified: true },
  { name: "Raghuveer Yashaswi", city: "Hyderabad", barId: "TS289/2019", court: "Warangal", verified: true },
  { name: "Khijar Ali Khan", city: "Rayachoty", barId: "AP/27/2019", court: "Courts", verified: true },
  { name: "Sanjeev Kumar", city: "Gajwel", barId: "AP/930/2011", court: "High Court", verified: true },
  { name: "Venkat Bala", city: "Chennai", barId: "Bar125", court: "High Court", verified: true },
  { name: "Adarsh Kandika", city: "Hyderabad", barId: "TS/2024", court: "Consultant", verified: true },
  { name: "BPR Law Chambers", city: "Delhi", barId: "R/4850/2023", court: "Delhi", verified: true },
  { name: "Adepu Venu", city: "Sircilla", barId: "TS/901/2010", court: "District Court Rajanna Sircilla", verified: true },
  { name: "Vijay Jyothula", city: "Vijayawada", barId: "AP/3663/2018", court: "High Court of AP", verified: true },
  { name: "Dr Syed Ussain Saheb", city: "Anantapur", barId: "AP/1230/2006", court: "Kurnool & High Court of AP", verified: true },
  { name: "Chandra Sekhar", city: "Nandyal", barId: "AP/13/1060", court: "Nandyal", verified: true },
  { name: "Ramesh Bhupathi", city: "Hyderabad", barId: "TS/1521/2011", court: "High Court", verified: true },
  { name: "Sivaprasad BNV", city: "Vijayawada", barId: "AP/1057-2013", court: "Civil Courts", verified: true },
  { name: "Mohan Akkam", city: "Vikarabad", barId: "TS/3131/2022", court: "Vikarabad District Court", verified: true },
  { name: "J Ashok", city: "Gadwal", barId: "TS/2097/2022", court: "Gadwal", verified: true },
  { name: "Rajashekar Reddy", city: "Hyderabad", barId: "TS/1643/2019", court: "All Courts", verified: true },
  { name: "Mohan Goud", city: "Hyderabad", barId: "TS/2642/2013", court: "Telangana High Court", verified: true },
  { name: "Hari Babu", city: "Visakhapatnam", barId: "AP/666/2024", court: "High Court", verified: true },
  { name: "Jagarapu Appalanaidu", city: "Visakhapatnam", barId: "AP/2688/2024", court: "Visakhapatnam", verified: true },
  { name: "Prasadarao Gondu", city: "Srikakulam", barId: "AP/1886/2009", court: "Srikakulam", verified: true },
  { name: "Vijay Shankar Vumnabad", city: "Hyderabad", barId: "TS/1428/2023", court: "Rangareddy District Court & High Court", verified: true },
  { name: "Seetharamanjaneyulu Kalluri", city: "Guntur", barId: "AP/3015/2016", court: "Guntur", verified: true },
  { name: "Budha Kusumanjali", city: "Vijayawada", barId: "AP/354/2023", court: "AP High Court", verified: true },
  { name: "Naga Raju Lanke", city: "Repalle", barId: "AP/1235/2022", court: "AP High Court", verified: true },
  { name: "Kadam Vinayak Prasad Devrao", city: "Bhainsa", barId: "TS 2165/2019", court: "Nirmal", verified: true },
  { name: "Singaluri Venkatesh", city: "Vijayawada", barId: "AP/894/2006", court: "Vijayawada", verified: true },
  { name: "Villa N V S Dora Babu", city: "Visakhapatnam", barId: "1129/2002", court: "High Court", verified: true },
  { name: "Koppaka Krishna", city: "Visakhapatnam", barId: "AP/4117/1999", court: "Visakhapatnam", verified: true },
  { name: "Suma Latha", city: "Lingamplly", barId: "TS/2773/2018", court: "Kukatpally Court", verified: true },
  { name: "Mudunuru Kethan Krishna", city: "Vijayawada", barId: "AP/3393/2024", court: "Vijayawada", verified: true },
  { name: "Veerendranath Srirangam", city: "Hyderabad", barId: "TS/604/2009", court: "Rangareddy Court, LB Nagar", verified: true },
  { name: "Suresh P", city: "Hyderabad", barId: "TS/1730/2022", court: "TS High Court", verified: true },
  { name: "Macha Raju", city: "Hyderabad", barId: "TS/1206/2023", court: "High Court of Telangana", verified: true },
  { name: "Ganne Ravi Kiran", city: "Narasaraopet", barId: "AP 685/2025", court: "Narasaraopet", verified: true },
  { name: "Bhanu Rekha", city: "Nandyal", barId: "1096/2025", court: "3rd Additional District Court", verified: true },
  { name: "Bhavani Prasad", city: "Hanumakonda", barId: "TS/1100/2021", court: "Hanumakonda", verified: true },
  { name: "Jagannath Reddy Bhuma", city: "Allagadda", barId: "AP/1003/2008", court: "Allagadda", verified: true },
  { name: "Gorantala Narsing Rao", city: "Secunderabad", barId: "TS/3382/2001", court: "All Courts — Secunderabad & Hyderabad", verified: true },
  { name: "Ravinder Reddy", city: "Hyderabad", barId: "TS1548/2020", court: "City Civil Court", verified: true },
  { name: "T Ramachandra", city: "Anantapur", barId: "1987", court: "Anantapur", verified: true },
  { name: "Chandra Sekhar", city: "Nuzvid", barId: "AP/3243/2018", court: "Nuzvid", verified: true },
  { name: "Tirupati Medari", city: "Hyderabad", barId: "TS/1680/2016", court: "City Civil & Criminal Court, Secunderabad", verified: true },
  { name: "Voleti Venkateswara Rao", city: "Kandukur", barId: "AP/1052/2021", court: "Kandukur", verified: true },
  { name: "Murali Vemula", city: "Bhimavaram", barId: "AP/1349/2021", court: "AP High Court", verified: true },
  { name: "Rajashekar Thogiti", city: "Metpally", barId: "TS/2594/2007", court: "SCJ & JCJ Metpally", verified: true },
  { name: "Shyamsundar K", city: "Ballari", barId: "Kar/2535/98", court: "Ballari District Court", verified: true },
  { name: "Thokala Mahender", city: "Hyderabad", barId: "TS/2961/2022", court: "Rangareddy", verified: true },
  { name: "Chandrasekhar Dhupam", city: "Repalle", barId: "AP/3200/2024", court: "High Court of Andhra Pradesh", verified: true },
  { name: "Pasula Giri", city: "Kurnool", barId: "AP/1533/2022", court: "Anantapur", verified: true },
  { name: "Ajay Kumar Mathangi", city: "Vijayawada", barId: "AP/792/2018", court: "Vijayawada", verified: true },
  { name: "Pavan Kumar", city: "Jangaon", barId: "TS/1366/2020", court: "Jangaon", verified: true },
  { name: "Satish Kumar P", city: "Kakinada", barId: "AP/270/2011", court: "Kakinada", verified: true },
  { name: "Hari Shankar", city: "Hyderabad", barId: "TS/2036/2020", court: "Kukatpally Court, Hyderabad", verified: true },
  { name: "Kalingiri Ramanjaneyulu", city: "Nandyala", barId: "AP/2568/2012", court: "Kurnool & Nandyal", verified: true },
  { name: "Vijay Naik", city: "Nandyala", barId: "AP/3053/2016", court: "Nandyala", verified: true },
  { name: "Bharath Reddy", city: "Anantapur", barId: "AP/2390/2018", court: "AP High Court", verified: true },
  { name: "Suresh Kumar Vemu", city: "Vijayawada", barId: "AP/1312/2019", court: "Vijayawada", verified: true },
  { name: "Lalita Karira", city: "Hyderabad", barId: "TS/1463-A/2015", court: "High Court & District Court", verified: true },
  { name: "Balivada Venkateswara Rao", city: "Visakhapatnam", barId: "1223/2025", court: "Bheemunipatnam", verified: true },
  { name: "Ramesh Banoth", city: "Hyderabad", barId: "TS/240/22", court: "Sangareddy, Kukatpally, LB Nagar, Medchal", verified: true },
  { name: "Sangeeta Mishra", city: "Hyderabad", barId: "MAH/183/1997", court: "High Court", verified: true },
  { name: "Pulukuri Raja Rathnam", city: "Adoni", barId: "AP/56/2013", court: "District Court", verified: true },
  { name: "Sridhar M Ayyalvar Ayyori", city: "Hyderabad", barId: "TS/2874/2012", court: "High Court", verified: true },
  { name: "Venkata Pratap Kumar", city: "Vijayawada", barId: "AP/433/2019", court: "AP HC & Vijayawada District Court", verified: true },
  { name: "S Raja Srinath Rao", city: "Karimnagar", barId: "TS1216/2019", court: "Karimnagar", verified: true },
  { name: "Raghavendrahari Nakka", city: "Bengaluru", barId: "AP/1255/2025", court: "Anantapur", verified: true },
  { name: "Shabana Munawar", city: "Hyderabad", barId: "TS/579/2018", court: "High Court of Telangana", verified: true },
  { name: "Chandrasekhar Varma N", city: "Vijayawada", barId: "AP/283/2023", court: "High Court of AP", verified: true },
  { name: "Sravani Vemuri", city: "Hyderabad", barId: "AP/2972/2024", court: "Ranga Reddy Court", verified: true },
  { name: "Srinivas Reddy Dodla", city: "Sangareddy", barId: "2943/2021", court: "Sangareddy", verified: true },
  { name: "Madhukar Eduru", city: "Gudur", barId: "AP/3062/2023", court: "Gudur", verified: true },
  { name: "Mohammed Mehtab Alam", city: "Hyderabad", barId: "2415/2024", court: "Rangareddy District Court", verified: true },
  { name: "Hari Rama Krishna Neelakantam", city: "Nalgonda", barId: "TS/138/2022", court: "Telangana High Court", verified: true },
  { name: "Kondronpally Giri Babu", city: "Hyderabad", barId: "9993", court: "Ranga Reddy District Court", verified: true },
  { name: "Sujata Karmakar", city: "Secunderabad", barId: "TS 785/1993", court: "All Courts in Telangana", verified: true },
  { name: "KVM Krishnamacharyulu", city: "Eluru", barId: "1263/2003", court: "District Court", verified: true },
  { name: "Jagadeesh Talikota", city: "Nandyal", barId: "AP/746/2016", court: "Nandyal, Kurnool, Allagadda Courts", verified: true },
  { name: "Yeduru Rajesh Reddy", city: "Vijayawada", barId: "AP/1922/2024", court: "AP High Court & District Courts", verified: true },
  { name: "Nabi Sab", city: "Adoni", barId: "KAR(P)/586/2024", court: "Siruguppa", verified: true },
  { name: "SaiRam Velisetti", city: "Rajahmundry", barId: "AP/729/2024", court: "Rajahmundry", verified: true },
  { name: "M Nagendra Babu", city: "Penukonda", barId: "AP/1414/2020", court: "Penukonda Bar Association", verified: true },
  { name: "Penchala Praneeth Dornadula", city: "Nellore", barId: "AP/84/2017", court: "Nellore", verified: true },
  { name: "Ruth Sharon Naicker", city: "Karimnagar", barId: "TS/526/2024", court: "Karimnagar", verified: true },
  { name: "Veerendranath Devaram", city: "Hyderabad", barId: "TS/2941/2015", court: "Telangana High Court", verified: true },
  { name: "Nagaveeranjaneyulu Kota", city: "Chilakaluripet", barId: "AP/2213/2019", court: "Chilakaluripet", verified: true },
  { name: "P Hussain Sani", city: "Adoni", barId: "AP/377/2021", court: "Adoni", verified: true },
  { name: "Shashidhar G D", city: "Hyderabad", barId: "309/1994", court: "All Courts — Hyderabad & Secunderabad", verified: true },
  { name: "Pochampally Giridhar", city: "Hyderabad", barId: "TS/3586/2001", court: "Ranga Reddy Court", verified: true },
  { name: "Mohammed Mujeeb", city: "Hyderabad", barId: "TS/1731/2016", court: "Criminal Court Hyderabad", verified: true },
  { name: "Nimmala Chandrasekhar", city: "Kothuru", barId: "AP/637/2021", court: "Kothuru", verified: true },
  { name: "Prashant Kumar Potturi", city: "Hyderabad", barId: "TS/2065/2005", court: "Medchal Malkajgiri District Court", verified: true },
  { name: "Adv Ankita Sonawale", city: "Aurangabad", barId: "MAH/13476/2025", court: "Aurangabad", verified: true },
  { name: "Janagani Karthik Goud", city: "Hanumakonda", barId: "TS 3052/2021", court: "All Courts in Telangana", verified: true },
  { name: "Amulya Dasari", city: "Rajahmundry", barId: "AP/613/2011", court: "Rajahmundry District Court", verified: true },
  { name: "Tallapenta Rambabu", city: "Eluru", barId: "AP/3647/2025", court: "Eluru", verified: true },
  { name: "Adrian Shaikh", city: "Mumbai", barId: "MAH/1650/2020", court: "High Court", verified: true },
  { name: "Sudheer J", city: "Hyderabad", barId: "TS/1688/2017", court: "Telangana High Court", verified: true },
  { name: "Rajashekhar Reddy", city: "Warangal", barId: "TS/1643/2018", court: "Warangal", verified: true },
  { name: "Zeus VJ", city: "Hyderabad", barId: "11223344556677", court: "Govt", verified: true },
  { name: "P N N Tagore", city: "Rajahmundry", barId: "AP/488/1999", court: "East Godavari", verified: true },
  { name: "Rajaswamy Aldandi", city: "Hyderabad", barId: "AP/784/2025", court: "Medchal-Malkajgiri District Court", verified: true },
  { name: "Santosh Sagar K", city: "Bangalore", barId: "TS/558/2020", court: "TS, AP, Karnataka", verified: true },
  { name: "Govardhan Gyara", city: "Hyderabad", barId: "TS/2387/2024", court: "RR Court", verified: true },
  { name: "Nizamkari Muralidhar", city: "Gadwal", barId: "TS/2909/2015", court: "Principal District Court, Gadwal", verified: true },
  { name: "Penagadam Suresh Kumar", city: "Tirupati", barId: "AP/4629/2026", court: "Tirupati", verified: true },
  { name: "Naveen Kumar", city: "Hyderabad", barId: "TS/2611/2025", court: "Ranga Reddy", verified: true },
  { name: "Ravinder Bheema", city: "Hyderabad", barId: "TS/2931/2022", court: "Hyderabad", verified: true },
  { name: "Narendra Nathreddy Vennapusa", city: "Mydukur", barId: "AP/2506/2016", court: "Proddatur", verified: true },
];

// ── REMAINING ADVOCATES (from original list, no Bar ID yet) ──
export const otherAdvocates: StaticAdvocate[] = [
  { name: "Rajashekar", city: "Hyderabad" },
  { name: "Advocate Kumar", city: "Hyderabad" },
  { name: "Ramakrishna Reddy Nimmala", city: "Hyderabad" },
  { name: "Suresh Kumar", city: "Hyderabad" },
  { name: "Gopa Surya Praksh", city: "Hyderabad" },
  { name: "Shaik Irshad", city: "Rayachoty" },
  { name: "Ramesh Challa", city: "Hyderabad" },
  { name: "Harish Kuma", city: "Hyderabad" },
  { name: "Hari K", city: "Hyderabad" },
  { name: "J Narsing Rao", city: "Gajwel" },
  { name: "Rajender P", city: "Hanumakonda" },
  { name: "T Rajeswari", city: "Vijayawada" },
  { name: "Hazaratali Syed", city: "Kakinada" },
  { name: "Sandeep Kumar Goli", city: "Kothagudem" },
  { name: "Satyanarayana Kethana", city: "Challapalli" },
  { name: "Veligotla Srinivasu", city: "Kakinada" },
  { name: "Sree Charan", city: "Hyderabad" },
  { name: "Shobha Rani Tadem", city: "Hyderabad" },
  { name: "Brundavan Gentela", city: "Achampet" },
  { name: "Kota Sambasiva Rao", city: "Narasaraopet" },
  { name: "Podamekala Mahesh", city: "Puttur" },
  { name: "Vishnu Reddy", city: "Guntur" },
  { name: "Venu Gopal", city: "Nirmal" },
  { name: "Venkat Rao", city: "Hyderabad" },
  { name: "Addagalla Sree Vidya", city: "Hyderabad" },
  { name: "Narumolla Praveen Kumar", city: "Hyderabad" },
  { name: "Mouli Pasunuti", city: "Warangal" },
  { name: "Salim Malik", city: "Kadapa" },
  { name: "Lakshmi Prasanna C", city: "Secunderabad" },
  { name: "Rajeshwar Raj", city: "Hyderabad" },
  { name: "Rajesh K", city: "Velagapudi" },
  { name: "Sultan Mahmood Ali", city: "Hyderabad" },
  { name: "Shodagiri Kiran", city: "Veerulapadu" },
  { name: "Vasantha Badugu", city: "Bhupalpally" },
  { name: "Keshav Rao", city: "Hyderabad" },
  { name: "Vinay Goud", city: "Sircilla" },
  { name: "Ravindranath K", city: "Kainada" },
  { name: "Abdul Khader", city: "Hyderabad" },
  { name: "Sk Ummar", city: "Macherla" },
  { name: "Vamsi Krishna Reddy Bommireddy", city: "Nandyal" },
  { name: "Anisetty Ravikishore", city: "Hyderabad" },
  { name: "Krishna Veni", city: "Vizag" },
  { name: "Vishnu Reddy Chinthaguntla", city: "Guntur" },
  { name: "V Raghava", city: "Hyderabad" },
];

// Combined: verified on top, others below
export const allStaticAdvocates: StaticAdvocate[] = [...verifiedAdvocates, ...otherAdvocates];
